### PR TITLE
Workflow dsl upgrade

### PR DESCRIPTION
**Pull request by sabre1041**
Updates to align with the latest CICD environment and brings in support for [Jenkins Workflow](https://wiki.jenkins-ci.org/display/JENKINS/Workflow+Plugin) plugin

@JaredBurck @etsauer please review

### CODE REVIEW

**Comment by sabre1041** [comment]
@JaredBurck can you give this a look over. Without these changes, the dsl is breaking for those with updated dsl plugins

**Comment by sabre1041** [comment]
Added documentation on required Maven repository configuration

**Comment by JaredBurck** [comment]
Cloned repo locally and imported into JBDS.  Project had a missing dependency for the jenkins job-dsl-core artifact. @sabre1041 added documentation for this issue (see above).

**Comment by etsauer** [comment]
@sabre1041 @JaredBurck can one of you provide steps for testing this?

**Comment by JaredBurck** [comment]
Verified that the 'pipeline' jobs finished successfully and were able to deploy/promote to all environments.  Also verified the 'workflow' job, but the job failed with a CredentialNotFoundException after verifying the application.  This was due to the chatOps credentials being null, which was true since the chatOps parameters were not set in the ose-jenkins-dsl.json file.  @sabre1041 added if check to fix these optional parameters.  The 'workflow' job was then able to finish successfully and to deploy/promote application to all environments.  This PR can now be merged.

**Pull request merged**
